CC = gcc
CFLAGS = -Wall -Wextra -std=c11
LIB_DIR = ../
INC_DIR = ../include

LIB_NAME = SML

# Compile and link the program
main: main.c
	$(CC) $(CFLAGS) -I$(INC_DIR) main.c -L$(LIB_DIR) -l$(LIB_NAME) -o main